### ISSUE TITLE
get_utxos() requiring asset shuffle

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#194]
There are references to this function, which doesn't include other wallet addresses and is requiring users to move assets before transaction can be completed.  This needs to be moved to a call on the backend where the API can handle this operation more intelligently.

staking.jsx
- 2 references in staking
- 2 references in unstaking

contribute/[round].jsx?
- there appears to be an old reference in the frontend code, but it may not be activte currently

**Comment by noob77777** [comment]
contribute and redeem have been updated.
