### ISSUE TITLE
remove funds from vesting contracts

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#217]
- [x] EGIO still outstanding (uses older contract, so need to contribute to buy rounds to get tokens)
_will need funds for this; can work with EGIO team on this_
- [x] Swamp Audio (currently in progress)
- [X] EXLE
- [X] Ergolend

**Comment by vikingphoenix** [comment]
Marty wants to do this on his own
- potentially use JSON to do this
- there is a tool that may help that Noob has made

**Comment by vikingphoenix** [comment]
One more with ergolend still (Lui)

**Comment by esot321c** [comment]
- EGIO still outstanding. 
- Ergolend need to be sent to Chris & team
- Need to figure out EXLE burn and EGIO burn
- Swamp Audio vesting next

**Comment by vikingphoenix** [comment]
converting task into new one to cleanup EGIO
