### ISSUE TITLE
Create Your DAO

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#231]
- Trappert building website

**Comment by vikingphoenix** [comment]
- Noob and Trappert still working on API
- Frontend is up/working

**Comment by vikingphoenix** [comment]
- web2 part mostly complete 6/14
- need help from smart contract: details, timeline @esot321c

**Comment by esot321c** [comment]
Meeting 11pm EDT Wednesday 
https://discord.com/events/890724659031576577/991385101596360704

**Comment by vikingphoenix** [comment]
waiting on ergowallet fixes

**Comment by vikingphoenix** [comment]
- need to integrate with S3
- just waiting to launch API
