### ISSUE TITLE
unspent optimized explorer

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#234]
- reveal more performance metrics
- support highly optimized API calls <1s
- handle staking
- handle vesting

**Comment by esot321c** [comment]
Went live on weekend. 

Work continues week of June 27th

- Some users report issues with the number of staked tokens display on front-end
-- Leif will improve load balancing to help rectify this issue
- Plan to replace all explorer endpoints with the new unspent explorer code
