### ISSUE TITLE
Bootstrap for SwampAudio

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#248]
- signup Lui for staker round

```json
{
  "roundName": "swampaudio staker",
  "tokenId": "02f31739e2e4937bb9afb552943753d1e3e9cdd1a5e5661949cb0cef93f907ea",
  "roundAllocation": 9200000,
  "vestingPeriods": 274,
  "vestingPeriodDuration_ms": 86400000,
  "cliff_ms": 0,
  "tokenSigUSDPrice": 0.010,
  "whitelistTokenMultiplier": 2,
  "sellerAddress": "9gpeMRQZvvAbqAmMowXS9zfkr4GCAQLgJs93N3ZotXUpC36TcLW",
  "tgeTime_ms": 1656619200000,
  "tgePct": 0,
  "roundEnd_ms": 1656619200000
}

{
  "roundName": "swampaudio seed",
  "tokenId": "02f31739e2e4937bb9afb552943753d1e3e9cdd1a5e5661949cb0cef93f907ea",
  "roundAllocation": 10800000,
  "vestingPeriods": 122,
  "vestingPeriodDuration_ms": 86400000,
  "cliff_ms": 0,
  "tokenSigUSDPrice": 0.020,
  "whitelistTokenMultiplier": 2,
  "sellerAddress": "9gpeMRQZvvAbqAmMowXS9zfkr4GCAQLgJs93N3ZotXUpC36TcLW",
  "tgeTime_ms": 1656619200000,
  "tgePct": 0,
  "roundEnd_ms": 1656619200000
}```

**Comment by Luivatra** [comment]
roundName should include token/project

**Comment by vikingphoenix** [comment]
{
  "Whitelist token id": "d601123e8838b95cdaebe24e594276b2a89cd38e98add98405bb5327520ecf6c",
  "Proxy NFT": "8b727bdec5759b7fa203df6b8324ad35998d49a5e281fb9703a8cbc7bcc35876",
  "NFT mint transaction": "4e405dfb30bfef0722d7397f60d95c791d08cf329ebcd0923e84973a6e42355e",
  "Whitelist token mint and token lock transaction": "a6f577f296800045587ac77fcef8d4d4601f0039e73c9fa926eb27b194be2896",
  "Proxy address": "4qyzRyJzKPEYP9XSTWsXH6hzhMCH1rMx5JvcYpVwWpD79bLDex79Bj6hbLR1NnVVYFFLCGCTSGQDQTkh5dm5d2BQY5bQRpf1AycoDjAEZyQwxiLRpbwB8Kiqyi7mUvb5UcJRdtUQ6sqcDZpgyf3hBUCCy2vg8e8P3wSopzkensJ4SoG86upev1TXacBRqsm54dshaMdToMAyFBLD2DMsZPP89gEZF4UAuLbRxZDiK871fT1NVCwa7pWK29ySAipERxWwno112zQoF5a9htj37VavXkYTzcZQ24iVjrkrfxU12huR9ZPkvLHkrdu8y8WgFdFr5oKFMsm2teFCrXMx8n9MUEEymFSWhMXBvg5UAkKW5ido9Zo2BYWDj81ew5fUoWhdJGGCu33SegnLzbNiB6VaRNusiZSPwLBA2NZ5yF5UJrUnMZAqPqWZb7zZ2zL2cBwSrFJ7kxSrQeaJ1RNGcQiDyXmzDE9vpyWTbG9W1mW5KzzMD4B9FZoUcRYbmFdp31H5Ho27rTNfx64tr7Crgjm7WfWVp8zPXjxfjW6su6u2GK6cx3feavARGNjyKKrYW3H8yPFi1Y9ruwmNwTyW96Z42FE1D28VuD5C2SJYmegbg9nPKc3ByUbS5CHJQQ4DLX9DdgZvbtq44VsiR2VmbpZNrjMwEHybRcoiDeLNhoPqxinXNvFNjg9gSca1C47EiYy4S94eFqbY1rrcF84siSEUq31e9A6snNTcDEiQ3efCcEyCb1JgA5iLDU7kqoi6xxCt7TKVfA96EKSczjaqBk5jvrmAhZrDpwrKm1sSf8py21tUgbdyDoJccUdRniahbibSRc5PVpukkkKtAUXEDG91qNbbuh47QA2NjSMiqNQjYGNJTaiBBDsGbxXjwgFkJA45E9FaFzvMvGuJyKJY9Yx9e6KBoSq1ktY38WHkFe7PBLwyZxUowb4fmgexLKiUWfLNzoZhHYu8DuAkgRtVoPRQxZYrqdgkg4PwAF6AE7XHVJEUr6iQHwTWVkp9LajbPXKtFQmVpnFNowcVVrVSabX5aqAmEu1PKVKJjvLwumUwoyRi6NwMqudVKAEqP3vdtmqr1KWzs9mNqgAybP8qaUM9pif9CxTGUKPR5FEsgnJv3WwvdJwbYv2J"
}

**Comment by vikingphoenix** [comment]
seed round 
```json 
{
  "Whitelist token id": "6b21ca866fce06a3b0b9aed2faea52a2201ae59b7db0666ce7d4e8c1d881a1fb",
  "Proxy NFT": "b91d8b77e147aed0fa67cdfbab681c23a2c02574472b7d73ca50aed19353363f",
  "NFT mint transaction": "41efd0eb422186e6b95052a30feb674ecf78c660deeced3ddf28d436c323eca9",
  "Whitelist token mint and token lock transaction": "362436d360b387e0fb967b2b5290149a240ffbf718b8c5c4ef3ffd8aaae75a25",
  "Proxy address": "4qyzRyJzKPEYP9XSTWsXH6hzhMCH1rMx5JvcYpVwWpD79bLDex79Bj6hbLR1NnVVYFFLCGCTSGQDQTkh5dm5d2BQY5bQRpf1AycoDjAEZyQwxiLRpbwB8Kiqyi7mUvb5UcJRdtUQ6sqcDZpgyf3hBUCCy2vg8e8P3wSopzkensJ4SoG86upev1TXacBRqsm54dshaMdToMAyFBLD2DMsZPP89gEZF4UAuLbRxZDiK871fT1NVCwa7pWK29ySAipERxWwno112zQoF5a9htj37VavXkYTzcZQ24iVjrkrfxU12huR9ZPkvLHkrdu8y8WgFdFr5oKFMsm2teFCrXMx8n9MUEEymFSWhMXBvg5UAkKW5ido9Zo2BYWDj81ew5fUoWhdJGGCu33SegnLzbNiB6VaRNusiZSPwLBA2NZ5yF5UJrUnMZAqPqWZb7zZ2zL2cBwSrFJ7kxSrQeaJ1RNGcQiDyXmzDE9vpyWTbG9W1mW5KzzMD4B9FZoUcRYbmFdp31H5Ho27rTNfx64tr7Crgjm7WfWVp8zPXjxfjW6su6u2GK6cx3feavARGNjyKKrYW3H8yPFi1Y9ruwmNwTyW96Z42FE1D28VuD5C2SJYmegbg9nPKc3ByUbS5CHJQQ4DLX9DdgZvbtq44VsiR2VmbpZNrjMwEHybRcoiDeLNhoPqxinXNvFNjg9gSca1C47EiYy4S94eFqbY1rrcF84siSEUq31e9A6snNTcDEiQ3efCcEyCb1JgA5iLDU7kqoi6xxCt7TKVfA96EKSczjaqBk5jvrmAhZrDpwrKm1sSf8py21tUgbdyDoJccUdRniahbibSRc5PVpukkkKtAUXEDG91qNbbuh47QA2NjSMiqNQjYGNJTaiBBDsGbxXjwgFkJA45E9FaFzvMvGuJyKJY9Yx9e6KBoSq1ktY38WHkFe7PBLwyZxUowb4fmgexLKiUWfLNzoZhHYu8DuAkgRtVoPRQxZYrqdgkg4PwAF6AE7XHVJEUr6iQHwTWVkp9LajbPXKtFQmVpnFNowcVVrVSabX5aqAmEu1PKVKJjvLwumUwoyRi6NwMqudVKAEqP3vdtmqr1KWzs9mNqgAybP8qaUM9pif9CxTGUKPR5FEsgnJv3WwvdJwbYv2J"
}```
