### ISSUE TITLE
Consolidate Derived Addresses in Wallet

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#249]
- addresses "move more erg to the key address"
- add ability to footer
- add link to error message
- will need frontend page

**Comment by esot321c** [comment]
Completed for staking staking page and dashboard

**Comment by vikingphoenix** [comment]
consider requesting this from nautilus rather than our site (should be wallet feature, not site feature)

**Comment by vikingphoenix** [comment]
https://github.com/capt-nemo429/nautilus-wallet/issues/61
