### ISSUE TITLE
Paideia websockets - notifications

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#274]
## Websockets for Paideia
- [x] Basic setup done with connection manager
- [x] ErgoAuth authenicated endpoint
- [x] Notifications
- [x] Proposal Discussions

```
export interface INotification {
  img: string;
  action: string;
  user_id: number;
  date: Date;
  is_read: bool;
  proposal_name: string;
  proposal_id: string;
  additional_text: string;
  id: number;
  href: string;
}
```

**Comment by esot321c** [comment]
Working on ErgoAuth to initiate API to notify the front-end of a successful tx signing. Still  in progress

**Comment by vikingphoenix** [comment]
- trappert has all proposals
- need a logging system for notifications (noob has built an activity log, that can be filtered for that user)
- trappert needs to write code to integrate websockets

**Comment by vikingphoenix** [comment]
outstanding 
- need to figure out general notifications
- backend for notifications work
- proposal and notification integration work
