### ISSUE TITLE
dainades: Dashboard

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#369]
## dainades: dashboard
- [x] optimize frontend dashboard to use unspent service instead of explorer
- [x] vesting/v1
- [x] vesting/v2
- [x] asset/balances
- [x] turn off cache invalidation microservice once this is live

**Comment by noob77777** [comment]
POST `/asset/balances`
would like the response body to change a bit
```
{
   "addresses": {
     "addr1": {...},
     "addr2": {...}
   }
   "total": 214,
   "price": 1.80 // ergo-usd
}
```
from
```
{
   "addr1": {},
   "addr2": {},
   "total": 214
}
```
having the addresses separately will help me iterate though them a bit nicely else have to explicitly filter for "total" and "price" while iterating over the keys
