### ISSUE TITLE
Paideia: ErgoAuth UI issues

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#382]
- [x] tested nautilus beta; works
- [x] test live webstore version

**Comment by vikingphoenix** [comment]
waiting for nautilus to have public version

**Comment by trappertribiani** [comment]
Nautilus & Ergo Mobile Wallet integrations are production ready for the frontend.

**Comment by noob77777** [comment]
We still need to wait till ergo-auth is available in the nautilus web-store version
