### ISSUE TITLE
pypy - test/use?

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#402]
# concerns

- works with fastapi?
- works with jpype?

**Comment by vikingphoenix** [comment]
concerns
- works with fastapi?
- works with jpype?

**Comment by Thrameos** [comment]
Thus far I have found no pypy developers willing to debug the issues interactions between pypy and jpype.  In theory it could be made to work, but currently they are far appart.  Python API is missing features that JPype needs so it must implement them which breaks pypy.

**Comment by vikingphoenix** [comment]
Moving to scala
