### ISSUE TITLE
Implement Bug Bounty program

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#484]
Need to determine task/cost

Alexis has some ideas on how to make this work and can share when ready

- [ ] for small tasks on website
- [ ] potentially for code

**Comment by esot321c** [comment]
- Alexis will make a task list and we will review to determine how many tokens per task
- Establish specific ranges for bugs

Await some specifics in a document or spreadsheet for next dev meeting (Nov 1).

**Comment by esot321c** [comment]
Suggest taking special consolation for security related bugs
