### ISSUE TITLE
Paideia API: Automate Activities and Notifications

### ISSUE THREAD

**Issue by noob77777** [ergo-pad/ergopad-api#499]
## Task Breakdown
- activities and notifications should be populated automatically

**Comment by michaelmirandi** [comment]
Activities
- Like a comment
- Dislike a comment
- Unlike / Undislike comment ?
- Favorited a proposal
- Unfavorited a proposal
- Created a proposal

**Comment by noob77777** [comment]
### notifications
Need to automate notifications for the following cases
- new comment on proposal
- new reply to comment
- comment is liked
- proposal is liked
- proposal is followed

**Comment by noob77777** [comment]
Activities
- https://github.com/ergo-pad/paideia-api/pull/28

**Comment by noob77777** [comment]
Notifications
- https://github.com/ergo-pad/paideia-api/pull/29

**Comment by esot321c** [comment]
notifications not yet integrated with new website. In progress

**Comment by Luivatra** [comment]
Noob waiting for info from @michaelmirandi
