### ISSUE TITLE
unspent endpoints

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#507]
- [ ] Endpoints to support BOTS
- [ ] Register to some sort of Danaides Network for defi

/asset/balance (for token and currency balances)
/asset/info/{asset_id}

/token/summary (metrics including supply, in circulation, market cap, etc..)
/token/config (misc values like stake pool, token id...)
/token/status (emission, total staked..)
/token/staking (staking metrics for addresses)
/token/vesting (vesting metrics for addresses)
/token/info/{token_id}

/box/info/{box_id}

/market/tvl

/status (current danaides metrics: current unspent boxes, current height, last X block time avgs, etc..)

Considering validation endpoints (may be unnecessary):
/validate/address (check if valid but also that it exists)
/validate/unspent (is block unspent

**Comment by noob77777** [comment]
lets have a cool name for this migration

**Comment by vikingphoenix** [comment]
needs updating @vikingphoenix
